(() => {
  "use strict";
  const D=window.ATHLETIC_DATA, KEY="athletic.bodyweight5k.v1";
  const $=s=>document.querySelector(s), esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  const iso=d=>{const x=new Date(d);x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)};
  const monday=d=>{const x=new Date(d);const n=(x.getDay()+6)%7;x.setDate(x.getDate()-n);x.setHours(0,0,0,0);return x};
  const defaultState=()=>({startDate:iso(monday(new Date())),weekOverride:null,dayOverride:null,logs:{},goals:{},settings:{shoulderLab:true,backLab:true},version:1});
  let state=load(), view="today", openModules=new Set(["warmup","strength","run"]), timer={left:0,total:0,id:null,label:"Rest"}, activeDemo=null;
  function load(){try{return {...defaultState(),...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{return defaultState()}}
  function save(){localStorage.setItem(KEY,JSON.stringify(state))}
  function weekNumber(){if(state.weekOverride)return +state.weekOverride;return Math.max(1,Math.min(16,Math.floor((monday(new Date())-monday(new Date(state.startDate+"T12:00:00")))/604800000)+1))}
  function activeDate(){return iso(new Date())}
  function dayNumber(){return state.dayOverride===null?new Date().getDay():+state.dayOverride}
  function phase(w=weekNumber()){return D.phases.find(p=>w>=p.from&&w<=p.to)||D.phases[3]}
  function schedule(day=dayNumber()){return D.schedule.find(x=>x.day===day)}
  function dayIndex(day=dayNumber()){return ({1:1,2:2,3:3,4:4,5:5,6:6,0:7})[day]}
  function log(){const k=activeDate();state.logs[k] ||= {date:k,week:weekNumber(),day:dayNumber(),checkin:{back:0,shoulder:0,knee:0,energy:"medium",tight:[]},exercises:{},notes:"",completed:false};return state.logs[k]}
  function formatTime(s){if(!Number.isFinite(s)||s<=0)return "—";const m=Math.floor(s/60),r=s%60;return `${m}:${String(r).padStart(2,"0")}`}
  function warmupItems(){
    const c=log().checkin, items=D.baseWarmup.map(x=>({...x}));
    const remove=id=>{const i=items.findIndex(x=>x.id===id);if(i>=0)items.splice(i,1)};
    if(c.back>=4){items.push(D.ex("breathing-extra","Extra 90/90 Breathing","60 sec","Slow exhales; flatten low back.",60));items.push(D.ex("tilt-holds","Posterior Tilt Holds","10 × 10 sec","Shorten the range if your back arches."));remove("hang")}
    if(c.shoulder>=4){items.push(D.ex("wall-slides","Wall Slides","2 × 12","Ribs down; reach long."));remove("hang")}
    if(c.tight.includes("ankles")){const a=items.find(x=>x.id==="ankle-wall"),s=items.find(x=>x.id==="squat-rock");a.target="3 × 10/ankle";s.target="90 sec";s.timer=90;items.push(D.ex("calf-iso","Calf Iso Stretch","30 sec/side","Heel down; hold steady.",30))}
    if(c.tight.includes("hips"))items.find(x=>x.id==="glute-bridge").target="3 × 10";
    if(c.tight.includes("thoracic")&&!items.some(x=>x.id==="wall-slides"))items.push(D.ex("wall-slides","Wall Slides","2 × 12","Ribs down; reach long."));
    return items;
  }
  function exerciseCard(x,module){const rec=log().exercises[x.id]||{};const high=(+rec.pain||0)>=4;return `<div class="exercise">
    <div class="ex-top"><input class="ex-check" type="checkbox" data-done="${esc(x.id)}" ${rec.done?"checked":""} aria-label="Complete ${esc(x.name)}"><div><div class="ex-name">${esc(x.name)}</div><div class="target">${esc(x.target)}</div>${x.cue?`<div class="cue">${esc(x.cue)}</div>`:""}</div><div class="ex-actions"><button class="btn small" data-demo="${esc(x.name)}">Demo</button>${x.timer?`<button class="btn small" data-timer="${x.timer}" data-label="${esc(x.name)}">Timer</button>`:""}</div></div>
    <div class="ex-fields"><div class="field"><label>Actual</label><input data-actual="${esc(x.id)}" value="${esc(rec.actual||"")}" placeholder="sets, reps, time or distance"></div><div class="field"><label class="${high?"pain-high":""}">Pain 0–10</label><input type="number" min="0" max="10" inputmode="numeric" data-pain="${esc(x.id)}" value="${esc(rec.pain??"")}"></div><div class="field notes"><label>Notes</label><input data-note="${esc(x.id)}" value="${esc(rec.note||"")}" placeholder="assistance, angle, load, form"></div></div></div>`}
  function moduleCard(id,title,subtitle,items,required=false){const open=openModules.has(id);return `<section class="card"><button class="module-toggle" data-module="${id}"><div><span class="tag ${required?"required":""}">${required?"Scheduled":"Optional"}</span><h2 class="section-title">${esc(title)}</h2><div class="sub">${esc(subtitle)}</div></div><span>${open?"Hide":"Open"}</span></button><div class="module-body" ${open?"":"hidden"}>${items.map(x=>exerciseCard(x,id)).join("")}</div></section>`}
  function renderToday(){const w=weekNumber(),p=phase(w),s=schedule(),l=log();let modules="";
    if(s.kind!=="recovery")modules+=moduleCard("warmup","Adaptive Warm-up","Back-safe setup: ribs down, pelvis controlled.",warmupItems(),true);
    if(s.kind==="strength")modules+=moduleCard("strength",s.title,"Skill first, then submaximal volume.",D.strengthFor(w,s.day),true);
    if(s.kind==="run"){const run=D.ex(`run-w${w}-d${s.day}`,s.title,D.runPlan[w-1][s.runIndex],s.runIndex===1?"Goal 5K pace is 6:00/km (9:39/mile).":"Keep easy running conversational.");modules+=moduleCard("run","Run",run.target,[run],true)}
    if(s.modules.includes("knee"))modules+=moduleCard("knee","ATG Science Knee Lab","Replaces duplicate lower-leg and knee accessories.",D.kneeLab,true);
    if(s.modules.includes("shoulder")&&state.settings.shoulderLab)modules+=moduleCard("shoulder","ATG Science Shoulder Lab","Selectable mobility-strength module.",D.shoulderLab,false);
    if(s.modules.includes("back")&&state.settings.backLab)modules+=moduleCard("back","ATG Science Back Lab","Selectable mobility-strength module.",D.backLab,false);
    if(s.kind==="recovery")modules=`<section class="card"><h2>Recovery day</h2><p class="sub">Walk, use easy mobility if it helps, and avoid turning recovery into another hard session.</p></section>`;
    return `<div class="hero"><div class="eyebrow">${new Date().toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric"})}</div><span class="day-tag">Day ${dayIndex()}</span><h1>${esc(s.title)}</h1><p><span class="phase">Week ${w} · ${p.name}</span> — ${esc(p.note)}</p></div>
      <section class="card"><div class="card-head"><div><h2 class="section-title">Readiness</h2><div class="sub">Adjust exercise range or assistance when pain changes.</div></div></div>
      <div class="checkin">${["back","shoulder","knee"].map(k=>`<div class="field"><label>${k[0].toUpperCase()+k.slice(1)} pain</label><input type="number" min="0" max="10" inputmode="numeric" data-check="${k}" value="${l.checkin[k]}"></div>`).join("")}</div>
      <div class="field" style="margin-top:10px"><label>Tight today</label><div class="chips">${["ankles","hips","thoracic"].map(k=>`<button class="chip ${l.checkin.tight.includes(k)?"active":""}" data-tight="${k}">${k[0].toUpperCase()+k.slice(1)}</button>`).join("")}</div></div>
      ${(l.checkin.back>=4||l.checkin.shoulder>=4||l.checkin.knee>=4)?`<div class="warning error">Pain is 4/10 or higher. Regress range/load and stop any movement that causes sharp or increasing pain.</div>`:""}</section>
      ${modules}
      <section class="card"><h2 class="section-title">Session notes</h2><textarea id="session-notes" placeholder="How did the session feel?">${esc(l.notes)}</textarea><div class="actions" style="margin-top:12px"><button class="btn primary" id="finish">${l.completed?"Session completed ✓":"Finish session"}</button></div></section>`}
  function renderGoals(){return `<div class="hero"><div class="eyebrow">Standards</div><h1>Your eight targets</h1><p>Update your current bests after a test. One-arm push-ups are 25 total, with sides kept roughly even.</p></div><section class="card"><div class="goal-grid">${D.goals.map(g=>{const v=state.goals[g.id];const shown=g.unit==="seconds"&&v?formatTime(+v):(v??"—");let pct=0;if(v!==undefined&&v!=="")pct=g.lower?Math.min(100,g.target/+v*100):Math.min(100,+v/g.target*100);return `<div class="stat"><span>${esc(g.name)}</span><strong>${shown}</strong><div class="bar"><i style="width:${pct}%"></i></div><div class="field" style="margin-top:9px"><label>Current best (${g.unit==="seconds"?"total seconds":g.unit})</label><input type="number" min="0" data-goal="${g.id}" value="${esc(v??"")}"></div><small class="fine">Goal: ${g.unit==="seconds"?"30:00":g.target+" "+g.unit}</small></div>`}).join("")}</div></section>`}
  function renderPlan(){const w=weekNumber();return `<div class="hero"><div class="eyebrow">16-week plan</div><h1>Week ${w}: ${phase(w).name}</h1><p>${phase(w).note}</p></div><section class="card"><div class="field"><label>Choose week</label><select id="week-preview">${Array.from({length:16},(_,i)=>`<option value="${i+1}" ${(i+1)===w?"selected":""}>Week ${i+1} · ${phase(i+1).name}</option>`).join("")}</select></div></section><section class="card"><div class="card-head"><div><span class="day-tag">Week ${w}</span><h2>${phase(w).name}</h2><div class="sub">Seven-day schedule</div></div></div><div class="day-list">${[1,2,3,4,5,6,0].map(d=>{const s=schedule(d);const run=s.kind==="run"?` · ${D.runPlan[w-1][s.runIndex]}`:"";return `<button class="day-link ${d===dayNumber()?"today":""}" data-day="${d}"><span class="day-num">D${dayIndex(d)}</span><span class="day-copy"><span class="day-tag">Day ${dayIndex(d)} · ${["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"][d]}</span><strong>${esc(s.title)}</strong><small>${s.kind==="strength"?"Bodyweight + Knee Lab":s.kind==="recovery"?"Walk + optional mobility":"Run"}${esc(run)}</small></span><span>›</span></button>`}).join("")}</div></section><section class="card"><h2>Testing rhythm</h2><p class="sub">Use Weeks 4, 8, 12 and 16 for progress checks. Stagger max tests across several days; do not test all eight standards in one session.</p></section>`}
  function renderProgress(){const logs=Object.values(state.logs).sort((a,b)=>b.date.localeCompare(a.date));const complete=logs.filter(x=>x.completed).length;const warm=logs.filter(x=>Object.keys(x.exercises||{}).some(k=>k==="breathing"&&x.exercises[k].done)).length;const avgPain=k=>{const a=logs.map(x=>+x.checkin?.[k]).filter(Number.isFinite);return a.length?(a.reduce((x,y)=>x+y,0)/a.length).toFixed(1):"—"};return `<div class="hero"><div class="eyebrow">History</div><h1>Progress</h1><p>Session history and readiness trends are stored only on this device.</p></div><div class="summary-grid"><div class="stat"><strong>${complete}</strong><span>completed sessions</span></div><div class="stat"><strong>${warm}</strong><span>warm-ups logged</span></div><div class="stat"><strong>${avgPain("knee")}</strong><span>average knee pain</span></div><div class="stat"><strong>${avgPain("shoulder")}</strong><span>average shoulder pain</span></div></div><section class="card"><h2>Recent sessions</h2>${logs.length?logs.slice(0,20).map(x=>`<div class="exercise"><span class="day-tag">Week ${x.week} · Day ${dayIndex(x.day)}</span><div class="ex-name">${esc(new Date(x.date+"T12:00:00").toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"}))} ${x.completed?"✓":""}</div><div class="sub">${esc(schedule(x.day)?.title||"Training")} · Pain B/S/K ${x.checkin?.back??0}/${x.checkin?.shoulder??0}/${x.checkin?.knee??0}</div></div>`).join(""):`<div class="empty">Complete your first session to start the history.</div>`}</section>`}
  function renderSettings(){return `<div class="hero"><div class="eyebrow">Program controls</div><h1>Settings</h1><p>Choose the plan start, optional modules and the day you want to train.</p></div><section class="card"><div class="field"><label>Week 1 starts</label><input id="start-date" type="date" value="${state.startDate}"></div><div class="field" style="margin-top:12px"><label>Temporarily show another week</label><select id="week-override"><option value="">Follow date automatically</option>${Array.from({length:16},(_,i)=>`<option value="${i+1}" ${+state.weekOverride===i+1?"selected":""}>Week ${i+1}</option>`).join("")}</select></div><div class="field" style="margin-top:12px"><label>Do another day today</label><select id="day-override"><option value="">Follow today automatically</option>${[1,2,3,4,5,6,0].map(d=>`<option value="${d}" ${state.dayOverride!==null&&+state.dayOverride===d?"selected":""}>${["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"][d]} — ${schedule(d).title}</option>`).join("")}</select></div></section><section class="card"><h2>Mobility-strength modules</h2><div class="exercise"><label><input type="checkbox" id="shoulder-setting" ${state.settings.shoulderLab?"checked":""}> Show Shoulder Lab on Tuesday</label></div><div class="exercise"><label><input type="checkbox" id="back-setting" ${state.settings.backLab?"checked":""}> Show Back Lab on Thursday</label></div></section><section class="card"><h2>Backup</h2><p class="sub">Safari data is local. Export regularly, especially before clearing browser data or changing phones.</p><div class="actions"><button class="btn" id="export">Export JSON</button><button class="btn" id="import">Import JSON</button><button class="btn danger" id="clear">Clear data</button></div><input id="import-file" type="file" accept="application/json" hidden></section><section class="card"><h2>Install on iPhone</h2><p class="sub">Open this app in Safari, tap Share, then Add to Home Screen. The app works offline after the first successful load.</p></section>`}
  function demoModal(){if(!activeDemo)return "";const d=window.ATHLETIC_DEMOS.get(activeDemo);return `<div class="modal" id="demo-backdrop"><section class="modal-card" role="dialog" aria-modal="true" aria-label="${esc(activeDemo)} demonstration"><div class="card-head"><div><div class="eyebrow">${d.exact?"Animated line guide":"General motion guide"}</div><h2>${esc(activeDemo)}</h2><div class="sub">${esc(d.label)}</div></div><button class="btn small" id="demo-close">Close</button></div><div class="demo-stage">${d.svg}</div><div class="demo-cue">${esc(d.cue)}</div>${d.exact?"":`<p class="demo-note">This exercise name does not specify the exact equipment or ATG variation. Use this for the general movement, then follow your program’s prescribed setup.</p>`}</section></div>`}
  function chrome(content){const w=weekNumber();return `<header class="topbar"><div class="topbar-inner"><div class="mark">A5</div><div><div class="eyebrow">Bodyweight + 5K</div><div class="top-title">Athletic</div></div><div class="week-pill">Week ${w} · Day ${dayIndex()} · ${phase(w).name}</div></div></header><main class="shell">${content}</main><nav class="tabs"><div class="tabs-inner">${[["today","●","Today"],["plan","▤","Plan"],["goals","◎","Goals"],["progress","↗","Progress"],["settings","⚙","Settings"]].map(([v,i,t])=>`<button class="tab ${view===v?"active":""}" data-view="${v}"><b>${i}</b>${t}</button>`).join("")}</div></nav>${timer.id?`<button class="timer-float" id="timer-open">${esc(timer.label)} · ${formatTime(timer.left)}</button>`:""}${demoModal()}`}
  function render(){const views={today:renderToday,plan:renderPlan,goals:renderGoals,progress:renderProgress,settings:renderSettings};$("#app").innerHTML=chrome(views[view]());bind()}
  function updateExercise(el,field){const id=el.dataset[field],r=log().exercises[id]||{};r[field==="done"?"done":field]=field==="done"?el.checked:el.value;log().exercises[id]=r;save()}
  function startTimer(sec,label){if(timer.id)clearInterval(timer.id);timer={left:+sec,total:+sec,label,id:setInterval(()=>{timer.left--;if(timer.left<=0){clearInterval(timer.id);timer.id=null;navigator.vibrate?.([160,80,160]);}render()},1000)};render()}
  function bind(){document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>{view=b.dataset.view;render();scrollTo(0,0)});document.querySelectorAll("[data-module]").forEach(b=>b.onclick=()=>{const id=b.dataset.module;openModules.has(id)?openModules.delete(id):openModules.add(id);render()});document.querySelectorAll("[data-done]").forEach(x=>x.onchange=()=>updateExercise(x,"done"));document.querySelectorAll("[data-actual]").forEach(x=>x.onchange=()=>updateExercise(x,"actual"));document.querySelectorAll("[data-pain]").forEach(x=>x.onchange=()=>updateExercise(x,"pain"));document.querySelectorAll("[data-note]").forEach(x=>x.onchange=()=>updateExercise(x,"note"));document.querySelectorAll("[data-timer]").forEach(x=>x.onclick=()=>startTimer(x.dataset.timer,x.dataset.label));document.querySelectorAll("[data-demo]").forEach(x=>x.onclick=()=>{activeDemo=x.dataset.demo;render()});
    document.querySelectorAll("[data-check]").forEach(x=>x.onchange=()=>{log().checkin[x.dataset.check]=Math.max(0,Math.min(10,+x.value||0));save();render()});document.querySelectorAll("[data-tight]").forEach(x=>x.onclick=()=>{const a=log().checkin.tight,k=x.dataset.tight;a.includes(k)?a.splice(a.indexOf(k),1):a.push(k);save();render()});
    document.querySelectorAll("[data-goal]").forEach(x=>x.onchange=()=>{state.goals[x.dataset.goal]=x.value;save();render()});document.querySelectorAll("[data-day]").forEach(x=>x.onclick=()=>{state.dayOverride=+x.dataset.day;save();view="today";render();scrollTo(0,0)});
    $("#session-notes")?.addEventListener("change",e=>{log().notes=e.target.value;save()});$("#finish")?.addEventListener("click",()=>{log().completed=!log().completed;save();render()});$("#week-preview")?.addEventListener("change",e=>{state.weekOverride=+e.target.value;save();render()});
    $("#start-date")?.addEventListener("change",e=>{state.startDate=e.target.value;state.weekOverride=null;save();render()});$("#week-override")?.addEventListener("change",e=>{state.weekOverride=e.target.value?+e.target.value:null;save();render()});$("#day-override")?.addEventListener("change",e=>{state.dayOverride=e.target.value===""?null:+e.target.value;save();render()});$("#shoulder-setting")?.addEventListener("change",e=>{state.settings.shoulderLab=e.target.checked;save()});$("#back-setting")?.addEventListener("change",e=>{state.settings.backLab=e.target.checked;save()});
    $("#export")?.addEventListener("click",()=>{const a=document.createElement("a"),u=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:"application/json"}));a.href=u;a.download=`athletic-backup-${activeDate()}.json`;a.click();URL.revokeObjectURL(u)});$("#import")?.addEventListener("click",()=>$("#import-file").click());$("#import-file")?.addEventListener("change",e=>{const f=e.target.files[0],r=new FileReader();r.onload=()=>{try{const v=JSON.parse(r.result);if(!v.logs)throw Error();state={...defaultState(),...v};save();render()}catch{alert("That backup could not be imported.")}};if(f)r.readAsText(f)});$("#clear")?.addEventListener("click",()=>{if(confirm("Clear all Athletic training data on this device?")){state=defaultState();save();render()}});$("#timer-open")?.addEventListener("click",()=>{if(confirm(`Stop ${timer.label} timer?`)){clearInterval(timer.id);timer.id=null;render()}});$("#demo-close")?.addEventListener("click",()=>{activeDemo=null;render()});$("#demo-backdrop")?.addEventListener("click",e=>{if(e.target.id==="demo-backdrop"){activeDemo=null;render()}})
  }
  if("serviceWorker" in navigator)addEventListener("load",()=>navigator.serviceWorker.register("./sw.js"));
  render();
})();
