(() => {
  "use strict";
  const D=window.ATHLETIC_DATA,KEY="athletic.bodyweight5k.v1",$=s=>document.querySelector(s);
  const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  const iso=d=>{const x=new Date(d);x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)};
  const monday=d=>{const x=new Date(d),n=(x.getDay()+6)%7;x.setDate(x.getDate()-n);x.setHours(0,0,0,0);return x};
  const uid=()=>`${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
  const defaults=()=>({version:4,startDate:iso(monday(new Date())),weekOverride:null,dayOverride:null,mode:"standard",sessions:{},activeSessionId:null,goals:{}});
  function migrate(raw){const next={...defaults(),...raw,sessions:{...(raw.sessions||{})}};if(raw.logs){Object.values(raw.logs).forEach(old=>{const id=`legacy-${old.date}-${old.day}`;next.sessions[id]={id,date:old.date,week:old.week||1,day:old.day,type:(D.schedule.find(x=>x.day===old.day)?.kind||"strength"),mode:"standard",runIndex:D.schedule.find(x=>x.day===old.day)?.runIndex??null,checkin:old.checkin||readiness(),exercises:old.exercises||{},run:{},notes:old.notes||"",completed:!!old.completed,createdAt:new Date(`${old.date}T12:00:00`).getTime(),startedAt:null,activeExerciseId:null,order:[]}});delete next.logs}Object.values(next.sessions).forEach(s=>{s.startedAt??=null;s.activeExerciseId??=null});next.version=4;return next}
  function load(){try{return migrate(JSON.parse(localStorage.getItem(KEY)||"{}"))}catch{return defaults()}}
  function save(){localStorage.setItem(KEY,JSON.stringify(state))}
  function readiness(){return {back:0,shoulder:0,knee:0,energy:"medium",tight:[]}}
  let state=load(),view="today",activeDemo=null,timer=null,timerId=null;
  const weekNumber=()=>state.weekOverride||Math.max(1,Math.min(16,Math.floor((monday(new Date())-monday(new Date(`${state.startDate}T12:00:00`)))/604800000)+1));
  const dayNumber=()=>state.dayOverride===null?new Date().getDay():+state.dayOverride;
  const dayIndex=d=>({1:1,2:2,3:3,4:4,5:5,6:6,0:7})[d];
  const dayName=d=>["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"][d];
  const schedule=d=>D.schedule.find(x=>x.day===d);
  const formatTime=s=>`${Math.floor(Math.max(0,s)/60)}:${String(Math.max(0,s)%60).padStart(2,"0")}`;
  function newSession({day=dayNumber(),type=schedule(day)?.kind||"strength",runIndex=null}={}){const id=uid(),s=schedule(day);if(type==="run"&&runIndex===null)runIndex=s?.runIndex??0;state.sessions[id]={id,date:iso(new Date()),week:weekNumber(),day,type:type==="recovery"?"recovery":type,runIndex,mode:state.mode||"standard",checkin:readiness(),exercises:{},run:{},notes:"",completed:false,createdAt:Date.now(),startedAt:null,activeExerciseId:null,order:[]};state.activeSessionId=id;save();return state.sessions[id]}
  function current(){let s=state.sessions[state.activeSessionId];if(!s)s=newSession();return s}
  const todaySessions=()=>Object.values(state.sessions).filter(s=>s.date===iso(new Date())).sort((a,b)=>a.createdAt-b.createdAt);
  function programDay(s){return s.type==="run"?[2,4,6][s.runIndex??0]:s.day}
  function workout(s=current()){return D.workoutFor(s.week,programDay(s),s.mode)}
  function setCount(x){if(x.sets)return x.sets;const m=String(x.target||"").match(/(\d+)(?:\s*[–-]\s*(\d+))?\s*[×x]/);return m?+(m[2]||m[1]):1}
  function orderedItems(s){const w=workout(s),items=[];w.warmup.forEach(x=>items.push({...x,module:"Warm-up",rest:20}));w.strength.forEach(x=>items.push({...x,module:"Main Strength",rest:90}));if(w.run)items.push({id:`run-w${s.week}-${s.runIndex}`,name:w.run.label,target:"Timer-guided run",cue:"Keep the run portions controlled enough to finish the entire prescription.",module:"Run",run:w.run});w.rehab.items.forEach(x=>items.push({...x,module:w.rehab.title,rest:45}));const byId=new Map(items.map(x=>[x.id,x])),ordered=(s.order||[]).map(id=>byId.get(id)).filter(Boolean);items.forEach(x=>{if(!ordered.some(y=>y.id===x.id))ordered.push(x)});return ordered}
  function estimate(s){const items=orderedItems(s);let sec=180;items.forEach(x=>{if(x.run){const runSeconds=x.run.segments.reduce((n,y)=>n+y.seconds,0);sec+=runSeconds||1800}else{const sets=setCount(x);sec+=sets*(x.module==="Main Strength"?150:x.module==="Warm-up"?75:90)}});return Math.max(1,Math.round(sec/60))}
  function previousRecord(s,id){return Object.values(state.sessions).filter(x=>x.id!==s.id&&x.createdAt<s.createdAt&&x.exercises?.[id]).sort((a,b)=>b.createdAt-a.createdAt)[0]?.exercises[id]}
  function recFor(s,id){return s.exercises[id]||{sets:[],pain:"",skipped:false}}
  function completion(rec,count){return rec.skipped?"Skipped":Array.from({length:count},(_,i)=>rec.sets?.[i]?.done).every(Boolean)?"Complete":`${(rec.sets||[]).filter(x=>x.done).length}/${count} sets`}
  function progression(rec,count){const done=(rec.sets||[]).filter(x=>x.done).length,pain=+rec.pain||0,rir=rec.rir===""||rec.rir===undefined?null:+rec.rir,quality=rec.quality||"";if(rec.skipped)return {tone:"hold",title:"Choose a workable version next time",why:"This movement was skipped, so progression is paused until a comfortable variation is completed."};if(pain>=4)return {tone:"regress",title:"Reduce range, load, or difficulty",why:`Pain was ${pain}/10. Use an easier variation and stop if symptoms sharpen or increase.`};if(done<count)return {tone:"hold",title:"Repeat this target",why:`You completed ${done} of ${count} planned sets. Build consistency before increasing difficulty.`};if(quality==="needs-work")return {tone:"hold",title:"Repeat and clean up technique",why:"All sets were completed, but technique needs work before progressing."};if(rir===null)return {tone:"input",title:"Add RIR and technique",why:"Log how many clean reps remained so the app can choose the next step."};if(rir<=1)return {tone:"hold",title:"Keep the same target",why:`With ${rir} rep${rir===1?"":"s"} in reserve, the current difficulty is already challenging enough.`};if(rir===2)return {tone:"progress",title:"Add 1 rep to each set",why:"All sets were clean with two reps in reserve—the right time for a small rep increase."};return {tone:"progress",title:"Add 1–2 reps or use a harder variation",why:`All sets were clean with ${rir} reps in reserve, so a controlled progression is appropriate.`}}
  function sessionStats(s){const items=orderedItems(s);let total=0,done=0;items.forEach(x=>{if(x.run){total++;if(s.run?.completed)done++}else{const count=setCount(x),rec=recFor(s,x.id);total+=count;done+=rec.skipped?count:(rec.sets||[]).filter(y=>y.done).length}});const elapsed=s.startedAt?Math.max(0,Math.floor((Date.now()-s.startedAt)/60000)):0,remaining=Math.max(0,Math.round(estimate(s)*(1-done/Math.max(1,total))));return {items,total,done,elapsed,remaining}}
  function activate(s,id){s.startedAt||=Date.now();s.activeExerciseId=id;save()}
  function setRows(s,x){const rec=recFor(s,x.id),count=setCount(x);return Array.from({length:count},(_,i)=>{const row=rec.sets?.[i]||{};return `<div class="set-row"><label class="set-check"><input type="checkbox" data-set-done="${esc(x.id)}" data-set-index="${i}" ${row.done?"checked":""}><span>Set ${i+1}</span></label><div class="field"><label>Reps / time</label><input data-set-field="reps" data-exercise-id="${esc(x.id)}" data-set-index="${i}" value="${esc(row.reps||"")}" placeholder="reps or time"></div><div class="field"><label>Weight</label><input data-set-field="weight" data-exercise-id="${esc(x.id)}" data-set-index="${i}" value="${esc(row.weight||"")}" placeholder="bodyweight"></div><div class="field set-notes"><label>Notes</label><input data-set-field="note" data-exercise-id="${esc(x.id)}" data-set-index="${i}" value="${esc(row.note||"")}" placeholder="assistance or form"></div></div>`}).join("")}
  function exerciseRollup(s,x,index,total){const rec=recFor(s,x.id),count=setCount(x),previous=previousRecord(s,x.id),next=progression(rec,count),open=s.activeExerciseId===x.id;return `<details class="exercise-rollup ${rec.skipped?"skipped":""}" data-exercise="${esc(x.id)}" ${open?"open":""}><summary><span class="exercise-order">${index+1}</span><span class="exercise-summary"><span class="module-label">${esc(x.module)}</span><strong>${esc(x.name)}</strong><small>${esc(x.target)} · ${completion(rec,count)}</small></span><span class="roll-arrow">⌄</span></summary><div class="exercise-body"><div class="cue">${esc(x.cue||"")}</div><div class="exercise-tools"><button class="btn small" data-demo-id="${esc(x.id)}" data-demo-name="${esc(x.name)}">Animated demo</button><button class="btn small" data-move="${esc(x.id)}" data-direction="up" ${index===0?"disabled":""}>↑ Earlier</button><button class="btn small" data-move="${esc(x.id)}" data-direction="down" ${index===total-1?"disabled":""}>↓ Later</button><button class="btn small ${rec.skipped?"primary":""}" data-skip="${esc(x.id)}">${rec.skipped?"Restore":"Skip"}</button></div>${previous?`<div class="previous"><span>Previous: ${esc(previous.sets?.map((r,i)=>`S${i+1} ${r.reps||"—"}${r.weight?` @ ${r.weight}`:""}`).join(" · ")||"logged")}</span><button class="btn small" data-copy="${esc(x.id)}">Copy</button></div>`:""}${setRows(s,x)}<div class="feedback-grid"><div class="field"><label>Reps in reserve</label><select data-feedback="rir" data-exercise-id="${esc(x.id)}"><option value="">Choose</option>${[0,1,2,3,4,5].map(v=>`<option value="${v}" ${String(rec.rir)===String(v)?"selected":""}>${v}</option>`).join("")}</select></div><div class="field"><label>Technique</label><select data-feedback="quality" data-exercise-id="${esc(x.id)}"><option value="">Choose</option><option value="clean" ${rec.quality==="clean"?"selected":""}>Clean</option><option value="needs-work" ${rec.quality==="needs-work"?"selected":""}>Needs work</option></select></div><div class="field"><label>Pain 0–10</label><input type="number" min="0" max="10" inputmode="numeric" data-pain="${esc(x.id)}" value="${esc(rec.pain??"")}"></div></div><div class="recommendation ${next.tone}"><span>Next time</span><strong>${esc(next.title)}</strong><p>${esc(next.why)}</p></div></div></details>`}
  function runRollup(s,x,index,total){const r=s.run||{},rpe=+r.rpe||0,next=!r.completed?"Complete the prescribed session before progressing.":rpe>=9?"Repeat or take an easy run before progressing.":rpe&&rpe<=6?"Proceed to the next scheduled run; keep it controlled.":"Proceed if recovery is normal; repeat if unusually fatigued.";return `<details class="exercise-rollup run-rollup" ${s.activeExerciseId===x.id||!s.activeExerciseId?"open":""} data-exercise="${esc(x.id)}"><summary><span class="exercise-order">${index+1}</span><span class="exercise-summary"><span class="module-label">Run</span><strong>${esc(x.name)}</strong><small>${esc(x.target)} · ${r.completed?"Complete":"Not started"}</small></span><span class="roll-arrow">⌄</span></summary><div class="exercise-body"><div class="run-prescription"><span>Week ${s.week} · Run ${(s.runIndex??0)+1}</span><strong>${esc(x.run.label)}</strong></div><button class="btn blue run-start" data-run-start="${esc(x.id)}">Start guided timer</button><div class="run-fields"><div class="field"><label>Distance</label><input data-run-field="distance" value="${esc(r.distance||"")}" placeholder="mi or km"></div><div class="field"><label>Total time</label><input data-run-field="time" value="${esc(r.time||"")}" placeholder="mm:ss"></div><div class="field"><label>RPE 1–10</label><input type="number" min="1" max="10" data-run-field="rpe" value="${esc(r.rpe||"")}"></div><div class="field"><label>Average pace</label><input data-run-field="pace" value="${esc(r.pace||"")}" placeholder="min/mi or min/km"></div></div><div class="recommendation ${rpe>=9?"regress":"progress"}"><span>Next run</span><strong>${esc(next)}</strong></div></div></details>`}
  function readinessCard(s){const high=Math.max(+s.checkin.back,+s.checkin.shoulder,+s.checkin.knee)>=4;return `<section class="card"><div class="card-head"><div><h2 class="section-title">Readiness</h2><div class="sub">Pain should change the plan, not just create a warning.</div></div></div><div class="checkin">${["back","shoulder","knee"].map(k=>`<div class="field"><label>${k[0].toUpperCase()+k.slice(1)} pain</label><input type="number" min="0" max="10" inputmode="numeric" data-check="${k}" value="${s.checkin[k]}"></div>`).join("")}</div>${high?`<div class="warning error">Pain is 4/10 or higher. Use the Short version, reduce range or load, and stop sharp or increasing pain.</div><button class="btn primary" id="use-short">Switch this session to Short</button>`:""}</section>`}
  function guidedBar(s,stats){const active=Math.max(0,stats.items.findIndex(x=>x.id===s.activeExerciseId)),hasActive=!!s.activeExerciseId;return `<aside class="guided-bar"><div class="guided-progress"><div><strong>${stats.done} of ${stats.total} sets</strong><span>${stats.elapsed} min elapsed · about ${stats.remaining} min left</span></div><div class="progress-ring" style="--pct:${Math.round(stats.done/Math.max(1,stats.total)*100)}%">${Math.round(stats.done/Math.max(1,stats.total)*100)}%</div></div><div class="guided-actions"><button class="btn" id="guide-prev" ${!hasActive||active===0?"disabled":""}>Previous</button><button class="btn" id="guide-rest">Rest</button><button class="btn primary" id="guide-next">${hasActive&&active===stats.items.length-1?"Finish":"Next exercise"}</button></div></aside>`}
  function renderToday(){const s=current(),w=workout(s),stats=sessionStats(s),items=stats.items,sessions=todaySessions();return `<div class="hero"><div class="eyebrow">${dayName(s.day)} · ${s.date}</div><span class="day-tag">Week ${s.week} · Day ${dayIndex(s.day)}</span><h1>${esc(s.type==="run"?`Run ${(s.runIndex??0)+1}`:w.schedule.title)}</h1><p><span class="phase">${esc(D.phaseFor(s.week).name)}</span> — estimated ${estimate(s)} minutes.</p></div><section class="card session-controls"><div class="field"><label>Today’s sessions</label><select id="session-picker">${sessions.map((x,i)=>`<option value="${x.id}" ${x.id===s.id?"selected":""}>${i+1}. ${x.type==="run"?`Run ${(x.runIndex??0)+1}`:schedule(x.day)?.title||"Workout"}${x.completed?" ✓":""}</option>`).join("")}</select></div><div class="mode-switch" role="group" aria-label="Workout length">${[["short","Short","25–35"],["standard","Standard","45–60"],["full","Full","60–75"]].map(([v,label,time])=>`<button class="chip ${s.mode===v?"active":""}" data-mode="${v}">${label}<small>${time} min</small></button>`).join("")}</div><div class="actions"><button class="btn" id="new-workout">New workout</button><select id="add-run-choice" aria-label="Choose run"><option value="0">Add Run 1</option><option value="1">Add Run 2</option><option value="2">Add Run 3</option></select><button class="btn" id="add-run">Add run</button></div></section>${readinessCard(s)}<section class="card workout-card"><div class="card-head"><div><h2 class="section-title">Guided workout</h2><div class="sub">Open any exercise, change the order, or use Next exercise to move through the session.</div></div><span class="workout-progress">${stats.done}/${stats.total}</span></div><div class="workout-list">${items.map((x,i)=>x.run?runRollup(s,x,i,items.length):exerciseRollup(s,x,i,items.length)).join("")}</div></section><section class="card"><h2 class="section-title">Session notes</h2><textarea id="session-notes" placeholder="How did the session feel?">${esc(s.notes)}</textarea><button class="btn primary finish" id="finish">${s.completed?"Session completed ✓":"Finish session"}</button></section>${guidedBar(s,stats)}${timerView()}`}
  function planDay(w,d){const s=schedule(d),sample={week:w,day:d,type:s.kind,runIndex:s.runIndex,mode:"standard",order:[]},work=D.workoutFor(w,d,"standard");return `<details class="plan-day"><summary><span class="day-num">D${dayIndex(d)}</span><span class="day-copy"><strong>${esc(s.title)}</strong><small>${s.kind==="run"?esc(work.run.label):s.kind==="strength"?`${work.strength.reduce((n,x)=>n+setCount(x),0)} strength sets + ${work.rehab.items.length} focused rehab exercises`:"15–25 min recovery"}</small></span><span class="details-arrow">⌄</span></summary><div class="plan-day-body">${s.kind==="run"?`<div class="run-prescription"><span>Timer guided</span><strong>${esc(work.run.label)}</strong></div>`:`<ul class="plan-exercises">${work.strength.map(x=>`<li><strong>${esc(x.name)}</strong><span>${esc(x.target)}</span></li>`).join("")}</ul>`}<button class="btn primary" data-open-day="${d}">Open Day ${dayIndex(d)}</button></div></details>`}
  function renderPlan(){const w=weekNumber();return `<div class="hero"><div class="eyebrow">16-week strength + 5K</div><h1>Week ${w}: ${esc(D.phaseFor(w).name)}</h1><p>${esc(D.phaseFor(w).note)}</p></div><section class="card"><div class="week-switcher"><button class="btn" id="week-prev" ${w===1?"disabled":""}>‹</button><select id="week-preview">${Array.from({length:16},(_,i)=>`<option value="${i+1}" ${w===i+1?"selected":""}>Week ${i+1} · ${esc(D.phaseFor(i+1).name)}</option>`).join("")}</select><button class="btn" id="week-next" ${w===16?"disabled":""}>›</button></div></section><section class="card"><h2 class="section-title">Running plan</h2><div class="sub">${w<=8?"Run/walk progression to your first completed 5K.":"PR phase: easy volume, pace work and a faster 5K attempt."}</div><div class="run-week">${D.runPlan[w-1].map((r,i)=>`<div class="run-plan-row"><span class="day-num">R${i+1}</span><div><strong>Workout ${i+1}</strong><p>${esc(r.label)}</p></div></div>`).join("")}</div></section><section class="card"><h2 class="section-title">Daily workouts</h2><div class="plan-days">${[1,2,3,4,5,6,0].map(d=>planDay(w,d)).join("")}</div></section>`}
  function renderGoals(){return `<div class="hero"><div class="eyebrow">Standards</div><h1>Your targets</h1><p>Update current bests after a test.</p></div><section class="card"><div class="goal-grid">${D.goals.map(g=>{const v=state.goals[g.id],shown=g.unit==="seconds"&&v?formatTime(+v):(v??"—");let pct=v!==undefined&&v!==""?(g.lower?Math.min(100,g.target/+v*100):Math.min(100,+v/g.target*100)):0;return `<div class="stat"><span>${esc(g.name)}</span><strong>${shown}</strong><div class="bar"><i style="width:${pct}%"></i></div><div class="field"><label>Current best (${g.unit})</label><input type="number" min="0" data-goal="${g.id}" value="${esc(v??"")}"></div></div>`}).join("")}</div></section>`}
  function renderProgress(){const sessions=Object.values(state.sessions).sort((a,b)=>b.createdAt-a.createdAt);return `<div class="hero"><div class="eyebrow">History</div><h1>Completed sessions</h1><p>Your detailed logs stay on this device.</p></div><section class="card">${sessions.length?sessions.map(s=>`<button class="history-row" data-session="${s.id}"><span><strong>${esc(s.type==="run"?`Run ${(s.runIndex??0)+1}`:schedule(s.day)?.title||"Workout")}</strong><small>${s.date} · Week ${s.week} · ${s.mode}</small></span><b>${s.completed?"✓":"Open"}</b></button>`).join(""):`<div class="empty">No sessions yet.</div>`}</section>`}
  function renderSettings(){return `<div class="hero"><div class="eyebrow">Controls</div><h1>Settings</h1><p>Change dates and protect your training history.</p></div><section class="card"><div class="field"><label>Week 1 starts</label><input id="start-date" type="date" value="${state.startDate}"></div><div class="field"><label>Preview week</label><select id="week-override"><option value="">Follow date</option>${Array.from({length:16},(_,i)=>`<option value="${i+1}" ${state.weekOverride===i+1?"selected":""}>Week ${i+1}</option>`).join("")}</select></div></section><section class="card"><h2>Backup</h2><p class="sub">Export regularly. Clearing browser website data removes local logs.</p><div class="actions"><button class="btn" id="export">Export JSON</button><button class="btn" id="import">Import JSON</button></div><input id="import-file" type="file" accept="application/json" hidden></section>`}
  function demoView(){if(!activeDemo)return "";const d=window.ATHLETIC_DEMOS.get(activeDemo.id,activeDemo.name),frame=activeDemo.frame||"play",phases=["Set up","Move","Finish"];return `<div class="modal" id="demo-backdrop"><section class="modal-card"><div class="card-head"><div><div class="eyebrow">Source-backed technique guide</div><h2>${esc(activeDemo.name)}</h2></div><button class="btn small" id="demo-close">Close</button></div><div class="demo-stage demo-frame-${frame}">${d.svg}<div class="demo-stage-label">${esc(frame==="play"?"Playing":frame[0].toUpperCase()+frame.slice(1))}</div></div><div class="demo-controls" role="group" aria-label="Animation controls">${[["play","▶ Play"],["start","Start"],["midpoint","Midpoint"],["finish","Finish"]].map(([v,label])=>`<button class="btn small ${frame===v?"primary":""}" data-demo-frame="${v}">${label}</button>`).join("")}</div><div class="demo-facts"><span><b>Tempo</b>${esc(d.tempo)}</span><span><b>Feel it</b>${esc(d.feel)}</span></div><div class="demo-steps">${d.steps.map((x,i)=>`<div><span>${i+1}</span><p><b>${phases[i]}</b>${esc(x)}</p></div>`).join("")}</div><div class="demo-cue"><strong>Key cue:</strong> ${esc(d.cue)}</div><div class="demo-mistake"><strong>Avoid:</strong> ${esc(d.mistake)}</div><div class="demo-options"><span><b>Easier</b>${esc(d.easier)}</span><span><b>Harder</b>${esc(d.harder)}</span></div><a class="demo-source" href="${esc(d.source.url)}" target="_blank" rel="noopener noreferrer"><span>Expert reference</span><strong>${esc(d.source.title)} ↗</strong></a><p class="demo-safety">Technique guidance is educational. Stop sharp or increasing pain and use professional assessment when symptoms persist.</p></section></div>`}
  function timerView(){if(!timer)return "";const seg=timer.segments?.[timer.index],title=timer.kind==="run"?(seg?.kind==="walk"?"Walk / easy":"Run"):"Rest";return `<div class="timer-modal"><section class="timer-card"><div class="eyebrow">${timer.kind==="run"?`Segment ${timer.index+1} of ${timer.segments.length}`:"Automatic rest"}</div><h2>${esc(title)}</h2><div class="timer-readout">${formatTime(timer.countUp?timer.elapsed:timer.left)}</div><div class="sub">${esc(timer.label)}</div><div class="actions"><button class="btn" id="timer-toggle">${timer.running?"Pause":"Resume"}</button>${timer.kind==="run"&&!timer.countUp?`<button class="btn" id="timer-skip">Next</button>`:""}<button class="btn danger" id="timer-stop">Stop</button></div></section></div>`}
  function shell(content){return `<header class="topbar"><div class="topbar-inner"><div class="mark"><img src="./icon-192.png" alt="" width="38" height="38"></div><div><div class="eyebrow">Bodyweight + 5K</div><div class="top-title">Athletic</div></div><div class="week-pill">Week ${weekNumber()} · ${esc(D.phaseFor(weekNumber()).name)}</div></div></header><main class="shell">${content}</main><nav class="tabs"><div class="tabs-inner">${[["today","●","Today"],["plan","▤","Plan"],["goals","◎","Goals"],["progress","↗","History"],["settings","⚙","Settings"]].map(([v,i,t])=>`<button class="tab ${view===v?"active":""}" data-view="${v}"><b>${i}</b>${t}</button>`).join("")}</div></nav>${demoView()}`}
  function render(){const views={today:renderToday,plan:renderPlan,goals:renderGoals,progress:renderProgress,settings:renderSettings};$("#app").innerHTML=shell(views[view]());bind()}
  function ensureRow(s,id,index){const rec=s.exercises[id]||{sets:[],pain:"",skipped:false};while(rec.sets.length<=index)rec.sets.push({reps:"",weight:"",note:"",done:false});s.exercises[id]=rec;return rec.sets[index]}
  function completeRunTimer(t){const s=state.sessions[t.sessionId];if(!s)return;s.run.completed=true;s.run.time=s.run.time||formatTime(t.elapsed);save()}
  function beginTimer(next){if(timerId)clearInterval(timerId);timer=next;timerId=setInterval(()=>{if(!timer?.running)return;timer.elapsed++;if(timer.countUp){render();return}timer.left--;if(timer.left<=0){navigator.vibrate?.([180,80,180]);if(timer.kind==="run"&&timer.index<timer.segments.length-1){timer.index++;timer.left=timer.segments[timer.index].seconds;timer.label=timer.segments[timer.index].kind==="walk"?"Recover, then get ready to run.":"Controlled running interval."}else{if(timer.kind==="run")completeRunTimer(timer);clearInterval(timerId);timerId=null;timer=null}}render()},1000);render()}
  function startRun(plan){const countUp=plan.segments[0].seconds===0;beginTimer({kind:"run",sessionId:current().id,segments:plan.segments,index:0,left:plan.segments[0].seconds,elapsed:0,countUp,running:true,label:plan.label})}
  function stopTimer(){if(timer?.kind==="run"&&timer.elapsed>0)completeRunTimer(timer);if(timerId)clearInterval(timerId);timerId=null;timer=null;render()}
  function bind(){
    document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>{view=b.dataset.view;render();scrollTo(0,0)});
    document.querySelectorAll("[data-mode]").forEach(b=>b.onclick=()=>{const s=current();s.mode=b.dataset.mode;state.mode=s.mode;s.order=[];save();render()});
    document.querySelectorAll("[data-check]").forEach(x=>x.onchange=()=>{current().checkin[x.dataset.check]=Math.max(0,Math.min(10,+x.value||0));save();render()});
    document.querySelectorAll(".exercise-rollup").forEach(x=>x.ontoggle=()=>{if(x.open){const s=current();activate(s,x.dataset.exercise)}});
    document.querySelectorAll("[data-set-field]").forEach(x=>x.oninput=()=>{const s=current();activate(s,x.dataset.exerciseId);const row=ensureRow(s,x.dataset.exerciseId,+x.dataset.setIndex);row[x.dataset.setField]=x.value;save()});
    document.querySelectorAll("[data-set-done]").forEach(x=>x.onchange=()=>{const s=current();activate(s,x.dataset.setDone);const row=ensureRow(s,x.dataset.setDone,+x.dataset.setIndex);row.done=x.checked;save();if(x.checked){const item=orderedItems(s).find(y=>y.id===x.dataset.setDone);beginTimer({kind:"rest",segments:[],index:0,left:item?.rest||60,elapsed:0,countUp:false,running:true,label:`Rest after ${item?.name||"set"}`})}else render()});
    document.querySelectorAll("[data-feedback]").forEach(x=>x.onchange=()=>{const s=current();s.exercises[x.dataset.exerciseId]||={sets:[],pain:"",skipped:false};s.exercises[x.dataset.exerciseId][x.dataset.feedback]=x.value;activate(s,x.dataset.exerciseId);render()});
    document.querySelectorAll("[data-pain]").forEach(x=>{x.oninput=()=>{const s=current();s.exercises[x.dataset.pain]||={sets:[],skipped:false};s.exercises[x.dataset.pain].pain=x.value;save()};x.onchange=render});
    document.querySelectorAll("[data-skip]").forEach(x=>x.onclick=()=>{const s=current();s.exercises[x.dataset.skip]||={sets:[],pain:""};s.exercises[x.dataset.skip].skipped=!s.exercises[x.dataset.skip].skipped;save();render()});
    document.querySelectorAll("[data-copy]").forEach(x=>x.onclick=()=>{const s=current(),old=previousRecord(s,x.dataset.copy);if(old)s.exercises[x.dataset.copy]=JSON.parse(JSON.stringify({...old,sets:(old.sets||[]).map(r=>({...r,done:false}))}));save();render()});
    document.querySelectorAll("[data-move]").forEach(x=>x.onclick=()=>{const s=current(),ids=orderedItems(s).map(y=>y.id),i=ids.indexOf(x.dataset.move),j=x.dataset.direction==="up"?i-1:i+1;if(j>=0&&j<ids.length){[ids[i],ids[j]]=[ids[j],ids[i]];s.order=ids;save();render()}});
    document.querySelectorAll("[data-demo-id]").forEach(x=>x.onclick=()=>{activeDemo={id:x.dataset.demoId,name:x.dataset.demoName,frame:"play"};render()});
    document.querySelectorAll("[data-run-start]").forEach(x=>x.onclick=()=>{const s=current(),item=orderedItems(s).find(y=>y.id===x.dataset.runStart);activate(s,x.dataset.runStart);startRun(item.run)});
    document.querySelectorAll("[data-run-field]").forEach(x=>x.oninput=()=>{current().run[x.dataset.runField]=x.value;save()});
    document.querySelectorAll("[data-open-day]").forEach(x=>x.onclick=()=>{state.dayOverride=+x.dataset.openDay;state.activeSessionId=null;save();view="today";render();scrollTo(0,0)});
    document.querySelectorAll("[data-session]").forEach(x=>x.onclick=()=>{state.activeSessionId=x.dataset.session;save();view="today";render()});
    document.querySelectorAll("[data-goal]").forEach(x=>x.oninput=()=>{state.goals[x.dataset.goal]=x.value;save()});
    $("#session-picker")?.addEventListener("change",e=>{state.activeSessionId=e.target.value;save();render()});
    $("#new-workout")?.addEventListener("click",()=>{newSession({day:current().day,type:schedule(current().day)?.kind||"strength"});render()});
    $("#add-run")?.addEventListener("click",()=>{newSession({day:current().day,type:"run",runIndex:+$("#add-run-choice").value});render()});
    $("#use-short")?.addEventListener("click",()=>{current().mode="short";current().order=[];save();render()});
    $("#session-notes")?.addEventListener("input",e=>{current().notes=e.target.value;save()});
    $("#finish")?.addEventListener("click",()=>{const s=current();s.completed=!s.completed;s.finishedAt=s.completed?Date.now():null;save();render()});
    $("#guide-prev")?.addEventListener("click",()=>{const s=current(),items=orderedItems(s),i=Math.max(0,items.findIndex(x=>x.id===s.activeExerciseId));s.activeExerciseId=items[Math.max(0,i-1)]?.id;activate(s,s.activeExerciseId);render();setTimeout(()=>document.querySelector(`[data-exercise="${CSS.escape(s.activeExerciseId)}"]`)?.scrollIntoView({behavior:"smooth",block:"center"}),0)});
    $("#guide-next")?.addEventListener("click",()=>{const s=current(),items=orderedItems(s),i=items.findIndex(x=>x.id===s.activeExerciseId);if(i===items.length-1){s.completed=true;s.finishedAt=Date.now();save();render();return}s.activeExerciseId=items[Math.min(items.length-1,i<0?0:i+1)]?.id;activate(s,s.activeExerciseId);render();setTimeout(()=>document.querySelector(`[data-exercise="${CSS.escape(s.activeExerciseId)}"]`)?.scrollIntoView({behavior:"smooth",block:"center"}),0)});
    $("#guide-rest")?.addEventListener("click",()=>beginTimer({kind:"rest",segments:[],index:0,left:60,elapsed:0,countUp:false,running:true,label:"Manual rest"}));
    $("#week-preview")?.addEventListener("change",e=>{state.weekOverride=+e.target.value;state.activeSessionId=null;save();render()});
    $("#week-prev")?.addEventListener("click",()=>{state.weekOverride=Math.max(1,weekNumber()-1);save();render()});$("#week-next")?.addEventListener("click",()=>{state.weekOverride=Math.min(16,weekNumber()+1);save();render()});
    $("#start-date")?.addEventListener("change",e=>{state.startDate=e.target.value;state.weekOverride=null;save();render()});$("#week-override")?.addEventListener("change",e=>{state.weekOverride=e.target.value?+e.target.value:null;save();render()});
    $("#export")?.addEventListener("click",()=>{const a=document.createElement("a"),u=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:"application/json"}));a.href=u;a.download=`athletic-backup-${iso(new Date())}.json`;a.click();URL.revokeObjectURL(u)});$("#import")?.addEventListener("click",()=>$("#import-file").click());$("#import-file")?.addEventListener("change",e=>{const f=e.target.files[0],r=new FileReader();r.onload=()=>{try{state=migrate(JSON.parse(r.result));save();render()}catch{alert("That backup could not be imported.")}};if(f)r.readAsText(f)});
    document.querySelectorAll("[data-demo-frame]").forEach(x=>x.onclick=()=>{activeDemo.frame=x.dataset.demoFrame;render()});
    $("#demo-close")?.addEventListener("click",()=>{activeDemo=null;render()});$("#demo-backdrop")?.addEventListener("click",e=>{if(e.target.id==="demo-backdrop"){activeDemo=null;render()}});
    $("#timer-toggle")?.addEventListener("click",()=>{timer.running=!timer.running;render()});$("#timer-skip")?.addEventListener("click",()=>{if(timer.index<timer.segments.length-1){timer.index++;timer.left=timer.segments[timer.index].seconds;render()}else stopTimer()});$("#timer-stop")?.addEventListener("click",stopTimer);
  }
  if("serviceWorker" in navigator)addEventListener("load",()=>navigator.serviceWorker.register("./sw.js"));
  render();
})();
