window.ATHLETIC_DEMOS = (() => {
  const base={
    push:{steps:["Set the hands and brace the body as one unit.","Lower with the elbows traveling diagonally back.","Press away without twisting, sagging, or shrugging."],cue:"Head, ribs, and hips move together.",mistake:"Elbows flaring or the trunk losing position."},
    pull:{steps:["Set a secure grip and controlled shoulder position.","Drive the elbows down as the body rises.","Lower smoothly without swinging or dropping."],cue:"Pull without reaching the chin.",mistake:"Shrugging or using momentum."},
    row:{steps:["Set a rigid body position and secure grip.","Pull the lower ribs toward the hands.","Pause, then lower without the hips dropping."],cue:"Keep the neck long and lead with the chest.",mistake:"Rotating, shrugging, or leading with the chin."},
    squat:{steps:["Plant the whole working foot and use support as needed.","Lower slowly while the knee tracks with the toes.","Drive through the full foot to return."],cue:"Use only the depth you can own.",mistake:"Knee collapse or dropping into the bottom."},
    hinge:{steps:["Stand with soft knees and a light brace.","Reach the hips backward while the spine stays long.","Drive the hips forward and finish tall."],cue:"Move through the hips, not the low back.",mistake:"Squatting down or rounding the back."},
    bridge:{steps:["Plant the feet and settle the ribs.","Tuck slightly and lift using the glutes.","Pause, then lower before the back takes over."],cue:"Finish with the hips, not a back arch.",mistake:"Flaring the ribs or pushing only through the toes."},
    core:{steps:["Set the ribs and pelvis before moving.","Move only as far as trunk control remains.","Return slowly, reset, and breathe."],cue:"Shorten the range before the back changes position.",mistake:"Using speed or holding the breath."},
    shoulder:{steps:["Stack the ribs and set the shoulder comfortably.","Move slowly through the prescribed arm path.","Stop before shrugging or arching, then return."],cue:"Reach long instead of forcing range.",mistake:"Flaring the ribs to gain motion."},
    handstand:{steps:["Set secure hands and a stable wall-supported position.","Lower through a pain-free pressing range.","Press away while keeping the ribs controlled."],cue:"End the set before position changes.",mistake:"Forcing depth or arching the low back."},
    walk:{steps:["Stand tall and begin with short, quiet steps.","Use a smooth rhythm at the prescribed pace.","Keep the effort controlled enough to finish."],cue:"Smooth rhythm matters more than speed.",mistake:"Overstriding or starting too fast."},
    ankle:{steps:["Keep the heel and foot arch controlled.","Move through the ankle without rolling the foot.","Pause at the end of the comfortable range."],cue:"Make the motion come from the ankle.",mistake:"Bouncing or creating fake range."},
    mobility:{steps:["Use support and establish a comfortable start position.","Ease into range while the pelvis and ribs stay controlled.","Pause, breathe, and return without bouncing."],cue:"The stretch should stay tolerable.",mistake:"Forcing range or twisting to move farther."},
    standing:{steps:["Set a stable stance and light brace.","Perform the named movement through a controlled range.","Pause, then return without momentum."],cue:"Keep the working joint aligned.",mistake:"Rushing or compensating elsewhere."}
  };
  const rows=`
breathing|core|4 sec in · 6 sec out|Lower ribs and deep abdomen|Feet supported higher|Add a gentle hamstring pull
glute-bridge|bridge|2 up · 2 hold · 3 down|Glutes and back of hips|Shorter range|Single-leg bridge
dead-bug|core|3 reach · 1 pause · 3 return|Deep abdomen|Move only the arms|Extend both limbs farther
ankle-wall|ankle|2 forward · 1 pause · 2 back|Front of the ankle|Move closer to wall|Move foot farther away
squat-rock|squat|3 down · gentle rocks · 3 up|Hips, ankles, inner thighs|Use more support|Use less support
hip-flexor|mobility|Ease in · hold 30 sec|Front of the kneeling-side hip|Smaller shift|Add overhead reach
hip-90|mobility|3 sec each direction|Deep hip rotation|Hands behind body|Hands off floor
hang|pull|Easy 20-sec hold|Lats and torso|Keep feet supported|Reduce foot support
oap|push|3 down · 1 pause · controlled up|Chest, triceps, anti-rotation core|Higher hand support|Lower hand support
hspu|handstand|3 down · pause · strong press|Shoulders and triceps|Pike push-up|Increase controlled depth
pushups|push|3 down · 1 pause · 2 up|Chest, triceps, trunk|Incline push-up|Feet-elevated push-up
push-volume|push|2 down · 1 pause · 2 up|Chest and triceps|Incline push-up|Harder angle
press-up|push|3 down · 1 pause · 2 up|Chest and triceps|Higher surface|Lower surface
pullups|pull|2 up · 1 hold · 3 down|Lats and upper back|Foot assistance|Add reps, then load
pull-volume|pull|2 up · 1 hold · 3 down|Lats, arms, upper back|Band assistance|Less assistance
rows-mon|row|2 pull · 1 hold · 3 lower|Mid-back and arms|More upright angle|Lower body angle
rows-wed|row|2 pull · 1 hold · 3 lower|Lats and mid-back|Higher incline|One-arm version
row-volume|row|2 pull · 1 hold · 3 lower|Mid-back, lats, arms|More upright angle|Feet elevated
pistol|squat|4 down · 1 pause · controlled up|Standing-leg quad and glute|Higher box or more support|Less support
pistol-fri|squat|4 down · 1 pause · smooth up|Quad, glute, foot|Box pistol|Less assistance
situps-wed|core|2 up · 3 down|Abdominals|Short-range curl-up|Longer lever
situp-volume|core|2 up · 3 down|Abdominals|Curl-up|Controlled load
knee-tread|walk|Continuous controlled steps|Quads and warmth around knees|Hold support|Longer duration
backward-tread|walk|Continuous easy rhythm|Legs warming without strain|Hold support|Longer duration
knee-flex|squat|2 bend · 1 pause · 3 return|Back of thigh and knee|Smaller range|Light resistance
knee-ext|standing|2 up · 2 hold · 3 down|Front of thigh|Smaller range|Light band resistance
knee-stability|standing|20-sec steady hold|Foot, hip, thigh stabilizers|Fingertip support|Add a small reach
step-forward|squat|3 down · 1 pause · 2 return|Front-leg quad and glute|Shorter supported step|Deeper controlled step
step-back|squat|3 down · 1 pause · 2 return|Front-leg glute and quad|Smaller supported step|Greater depth
step-side|squat|2 step · 2 control · 2 return|Side glute and thigh|Smaller step|Band resistance
mobilize|mobility|3 down · pause · 3 up|Hip, ankle, front thigh|Shorter range|Deeper range
posterior-chain|hinge|3 back · 1 pause · 2 stand|Hamstrings and glutes|Hands supported|Single-leg hinge
long-calf|ankle|2 up · 2 hold · 3 down|Upper calf|Two-leg raise|Single-leg with load
short-calf|ankle|2 up · 2 hold · 3 down|Lower calf and Achilles|Two-leg raise|Single-leg with load
front-shins|ankle|2 up · 1 hold · 3 down|Front of shins|More upright stance|Feet farther from wall
shoulders-out|shoulder|2 out · 2 hold · 3 in|Back of shoulders|No resistance|Light band
wall-slides|shoulder|3 up · 1 pause · 3 down|Serratus and upper back|Shorter slide|Light band
scap-pull|pull|2 lift · 2 hold · 3 lower|Lower traps and lats|Feet assisted|Longer holds
shoulder-stability|shoulder|20-sec steady hold|Shoulder and trunk stabilizers|More upright support|Lower support
wrist-flex|shoulder|2 up · 1 hold · 3 down|Front of forearm|No load|Very light load
back-one-leg|standing|2 back · 2 hold · 3 return|Glute of moving leg|Smaller range|Light band
back-hip-flex|mobility|Ease in · hold · ease out|Front of back-side hip|Smaller shift|Overhead reach
back-two-leg|bridge|2 up · 20-sec hold · 3 down|Both glutes|Shorter hold|Bridge march
spine|mobility|4 sec each direction|Gentle motion across spine|Smaller range|Add breathing pauses`;
  const specs={};rows.trim().split("\n").forEach(line=>{const [id,type,tempo,feel,easier,harder]=line.split("|");specs[id]={type,tempo,feel,easier,harder}});
  const exact={
    breathing:{steps:["Lie on your back with feet supported and knees near 90°.","Inhale quietly into the sides and back of the ribs.","Exhale slowly until the ribs settle; pause before the next breath."],cue:"Make the exhale longer than the inhale.",mistake:"Forcing the back flat or shrugging."},
    "ankle-wall":{steps:["Plant the whole foot a short distance from the wall.","Drive the knee toward the wall in line with the middle toes.","Touch gently, then return while the heel stays down."],cue:"Move the knee forward without losing the arch.",mistake:"Lifting the heel or collapsing the foot inward."},
    oap:{steps:["Choose a wall, bench, or floor height that keeps the shoulders level.","Lower the chest as one unit while resisting rotation.","Press away without twisting the hips or ribs."],cue:"Raise the support when the body stops moving as one piece.",mistake:"Opening the hips or dropping one shoulder."},
    hspu:{steps:["Set the hands securely and establish a controlled wall position.","Lower only through the range the shoulders can own.","Press the floor away while keeping the ribs controlled."],cue:"End the set before position changes.",mistake:"Overarching the back or forcing depth."},
    pistol:{steps:["Use a post, strap, or counter for enough assistance.","Sit down and back over the working foot as the free leg reaches forward.","Keep the whole foot planted and stand smoothly."],cue:"Own the range before reducing assistance.",mistake:"Knee collapse or dropping into the bottom."},
    "knee-tread":{steps:["Set a slow treadmill or choose a clear walking path.","Take short backward steps, contacting with the forefoot first.","Keep the torso tall and maintain a smooth rhythm."],cue:"Short, quiet steps matter more than speed.",mistake:"Taking long steps or letting the belt pull you."},
    "wall-slides":{steps:["Stand with ribs stacked and forearms supported on the wall.","Slide upward while gently reaching into the wall.","Stop before shrugging or arching, then return."],cue:"Reach long rather than forcing the hands flat.",mistake:"Flaring the ribs to fake overhead range."},
    "posterior-chain":{steps:["Stand with soft knees and brace lightly.","Push the hips backward while keeping the spine long.","Drive the hips forward and finish tall."],cue:"Reach the hips back as the chest travels forward.",mistake:"Squatting down or rounding the back."}
  };
  Object.assign(exact,{
    "glute-bridge":{steps:["Lie on your back with knees bent, feet flat, and arms relaxed.","Brace the abdomen and squeeze the glutes to raise the hips until shoulders, hips, and knees align.","Hold without arching, then lower the spine and hips under control."],cue:"Keep the ribs down as the hips rise.",mistake:"Pushing the hips higher by extending the low back."},
    "dead-bug":{steps:["Lie on your back with arms vertical and hips and knees at 90°.","Brace, then lower the opposite arm and leg only as far as the trunk stays still.","Return to the start and alternate without rushing."],cue:"Exhale during the reach and keep the ribs heavy.",mistake:"Letting the low back lift or the ribs flare."},
    "squat-rock":{steps:["Hold a secure support and place the feet in a comfortable squat stance.","Sit between the hips while the whole foot remains planted.","At the bottom, make small controlled shifts before driving through both feet to stand."],cue:"Let the knees track naturally in line with the toes.",mistake:"Forcing depth after the heels or arches lose contact."},
    "hip-flexor":{steps:["Kneel on one knee with the other foot forward and both hips facing ahead.","Gently tuck the pelvis and squeeze the glute on the kneeling side.","Shift the body forward slightly without arching the back."],cue:"Tuck first, then move forward only a little.",mistake:"Leaning the ribs back to create more range."},
    "hip-90":{steps:["Sit tall with both knees bent and feet wider than hip width.","Rotate both thighs toward one side while keeping both sitting bones as heavy as possible.","Return through center and rotate to the other side under control."],cue:"Use the hands behind you until the hips can move without the spine twisting.",mistake:"Dropping rapidly or forcing the knees to the floor."},
    hang:{steps:["Grip a secure bar with feet still able to reach support if needed.","Lengthen the body while keeping a small amount of shoulder and abdominal tension.","Breathe normally, then step down instead of dropping."],cue:"Use an active, comfortable shoulder position.",mistake:"Relaxing suddenly into a painful shoulder pinch."},
    pushups:{steps:["Place the hands slightly wider than shoulder width and form a straight line from head to heels.","Brace the trunk and lower the chest while the elbows travel diagonally back.","Press the floor away until the elbows straighten without the hips sagging."],cue:"Move the head, ribs, and hips as one unit.",mistake:"Hiking the hips, sagging the back, or losing hand pressure."},
    "push-volume":{steps:["Choose a push-up height that leaves about two clean repetitions available.","Lower the chest to the same depth on every repetition.","Press to a stable top position and end the set before speed or alignment changes."],cue:"Make the last repetition look like the first.",mistake:"Starting with a maximum-effort set and shortening later reps."},
    "press-up":{steps:["Place both hands on a stable elevated surface and step into a straight-body plank.","Lower the chest toward the edge while maintaining full-foot and hand pressure.","Press back to the start without shrugging or letting the hips trail."],cue:"Raise the surface if the shoulder or trunk position changes.",mistake:"Letting the elbows flare straight sideways."},
    pullups:{steps:["Begin in a controlled hang with the hands secure and elbows straight.","Set the shoulder blades, then drive the elbows down to raise the body.","Reach the chin above the bar without craning, then lower to straight arms under control."],cue:"Initiate with the shoulder blades before bending the elbows.",mistake:"Swinging, kicking, or reaching the neck over the bar."},
    "pull-volume":{steps:["Start each repetition from the same straight-arm shoulder position.","Pull the elbows down while the legs and trunk remain quiet.","Lower for the full planned range and stop before momentum appears."],cue:"Keep two clean repetitions in reserve.",mistake:"Turning later repetitions into swings or partial reps."},
    "rows-mon":{steps:["Set a secure grip and walk the feet until the body forms a rigid incline.","Pull the lower ribs toward the bar or handles while the hips remain aligned.","Pause briefly, then straighten the arms without losing body tension."],cue:"Start with the shoulder blades, then bend the elbows.",mistake:"Leading with the chin or letting the hips fold."},
    "rows-wed":{steps:["Set the prescribed incline or one-arm support with the hips and ribs square.","Pull the elbow toward the back pocket while the shoulder stays away from the ear.","Lower until the arm is long and the shoulder blade can move forward under control."],cue:"Keep the torso still while the shoulder blade moves.",mistake:"Rotating the ribs to manufacture the last part of the pull."},
    "row-volume":{steps:["Choose and remember one body angle for every set.","Pull the chest toward the same point on the bar or handles.","Lower to full arm length and stop the set before the angle or range changes."],cue:"Standardize the body angle and touch point.",mistake:"Standing more upright as fatigue builds."},
    "pistol-fri":{steps:["Plant the working foot and hold only as much support as needed.","Reach the free leg forward while sitting the hips down over the working foot.","Pause at the controlled depth and stand without bouncing or pulling hard with the arms."],cue:"Keep pressure through the heel, big toe, and little toe.",mistake:"Losing the foot tripod or allowing the knee to collapse inward."},
    "situps-wed":{steps:["Lie with knees bent and establish the same foot and arm position for every set.","Exhale and curl the trunk upward without pulling the head forward.","Reach the chosen top standard, then lower the spine under control."],cue:"Use one repeatable start and finish position.",mistake:"Jerking from the neck or falling through the lowering phase."},
    "situp-volume":{steps:["Choose a range that remains comfortable for the low back.","Rise smoothly to the same top position on each repetition.","Lower under control and stop before speed or range changes."],cue:"Accumulate identical repetitions, not rushed repetitions.",mistake:"Using momentum to extend the set."},
    "backward-tread":{steps:["Use a clear path or set the treadmill very slowly before stepping on.","Hold support lightly and take short backward steps with the torso upright.","Maintain a smooth rhythm, then stop the belt before stepping off."],cue:"Control each foot placement instead of letting the belt pull you.",mistake:"Overstriding, leaning back, or using excessive speed."},
    "knee-flex":{steps:["Stand tall with stable support and the thighs aligned.","Bend one knee to bring the heel toward the buttock without moving the thigh forward.","Pause at the comfortable limit, then lower the foot slowly."],cue:"Keep both knees pointing down.",mistake:"Arching the back or swinging the lower leg."},
    "knee-ext":{steps:["Sit tall with the thigh supported and the knee bent.","Straighten the knee smoothly until the quadriceps contracts.","Pause without snapping the joint locked, then lower slowly."],cue:"Lift and lower with the front of the thigh.",mistake:"Swinging the leg or dropping it on the return."},
    "knee-stability":{steps:["Stand near support and establish heel, big-toe, and little-toe contact.","Shift onto one leg with a soft knee and level pelvis.","Hold the knee over the middle toes while breathing normally."],cue:"Make the foot and pelvis quiet before reducing support.",mistake:"Gripping the toes or allowing the pelvis to drop."},
    "step-forward":{steps:["Stand tall and step forward far enough for the whole front foot to land.","Lower under control while the front knee tracks with the toes.","Push through the front foot to return to the starting stance."],cue:"Land softly and let the front leg absorb the step.",mistake:"Slamming the foot down or pushing mostly from the back leg."},
    "step-back":{steps:["Stand tall and reach one foot backward onto the ball of the foot.","Lower straight down while the front foot stays fully planted.","Drive through the front leg to bring the feet together again."],cue:"Keep most of the work in the front leg.",mistake:"Twisting the front knee or pushing excessively from the back foot."},
    "step-side":{steps:["Begin tall with the feet parallel and knees soft.","Step sideways, keep the toes forward, and control the pelvis over the stepping leg.","Push the floor away and return without dragging the other foot."],cue:"Keep the knees and toes facing the same direction.",mistake:"Letting the knee cave inward or the pelvis drop."},
    mobilize:{steps:["Take a split stance and hold stable support.","Lower straight down until the front ankle, knee, and hip reach a comfortable range.","Pause without bouncing, then push through the front foot to rise."],cue:"Use the support to keep the pelvis square.",mistake:"Twisting the front knee to gain more depth."},
    "long-calf":{steps:["Stand tall on the working foot with the knee straight and support nearby.","Press through the big-toe side of the forefoot to raise the heel.","Pause at the top, then lower the heel slowly through the available range."],cue:"Keep the ankle centered instead of rolling outward.",mistake:"Bouncing or bending the knee as fatigue builds."},
    "short-calf":{steps:["Bend the working knee and keep it bent throughout the repetition.","Raise the heel while maintaining pressure across the forefoot.","Pause, then lower slowly without straightening the knee."],cue:"The bent knee shifts the emphasis toward the soleus.",mistake:"Letting the knee straighten or the ankle roll outward."},
    "front-shins":{steps:["Stand with the back supported and heels planted slightly in front.","Lift the forefeet and toes toward the shins without rocking the hips.","Pause high, then lower the feet slowly instead of dropping them."],cue:"The heels stay heavy for the entire set.",mistake:"Rocking the whole body to lift the toes."},
    "shoulders-out":{steps:["Stand or sit tall with elbows bent 90° and held near the sides.","Keeping the elbows still, rotate the hands outward through a comfortable range.","Pause with the shoulder blades steady, then return slowly."],cue:"Rotate at the shoulder without arching the ribs.",mistake:"Pulling the elbows backward or shrugging."},
    "scap-pull":{steps:["Hang with a secure grip, straight elbows, and feet supported if needed.","Without bending the elbows, pull the shoulder blades down to raise the body slightly.","Pause, then return to the controlled hang."],cue:"This is a shoulder-blade movement, not a short pull-up.",mistake:"Bending the elbows or craning the neck."},
    "shoulder-stability":{steps:["Choose a pain-free wall, bench, or floor support position.","Stack the shoulder and press evenly into the support.","Hold the trunk and shoulder quiet while breathing normally."],cue:"Create steady pressure without shrugging.",mistake:"Sinking into the shoulder or holding the breath."},
    "wrist-flex":{steps:["Support the forearm with the palm up and the wrist free beyond the edge.","Curl the palm toward the forearm without lifting the elbow.","Pause, then lower the hand through a comfortable range."],cue:"Use a light load and keep the forearm still.",mistake:"Moving the whole arm or forcing wrist range."},
    "back-one-leg":{steps:["Hold support, stand tall, and keep both hip bones facing forward.","Move one straight leg backward from the hip without leaning or arching.","Squeeze the glute briefly, then return the toes beside the standing foot."],cue:"A smaller hip-only movement is more useful than a large back arch.",mistake:"Turning the toes out or tipping the trunk forward."},
    "back-hip-flex":{steps:["Set a half-kneeling or split stance with stable support.","Tuck the pelvis and squeeze the glute of the back leg.","Shift forward slightly until the front of that hip stretches, then return."],cue:"Keep the belt line level and ribs stacked.",mistake:"Creating the stretch by arching the low back."},
    "back-two-leg":{steps:["Lie with knees bent, feet flat, and ribs relaxed.","Brace lightly and lift until shoulders, hips, and knees form one line.","Maintain the hold with the glutes, then lower under control."],cue:"Stop the lift when the hips reach neutral.",mistake:"Holding the position by extending the low back."},
    spine:{steps:["Set up comfortably on hands and knees with the head in line with the spine.","Slowly round the spine segment by segment through a pain-free range.","Reverse the motion gently without dropping into the low back."],cue:"Match the movement to slow breathing.",mistake:"Forcing the end range or moving abruptly."}
  });
  const refs={
    ace:{title:"ACE Exercise Library",url:"https://www.acefitness.org/resources/everyone/exercise-library/"},
    push:{title:"ACE: Push-Up Technique",url:"https://www.acefitness.org/resources/everyone/exercise-library/41/push-up/"},
    nasmPush:{title:"NASM: Push-Up Form",url:"https://blog.nasm.org/nasm-guide-to-push-ups/form-and-technique"},
    nasmPull:{title:"NASM: Pull-Ups and Chin-Ups",url:"https://www.nasm.org/resource-center/blog/chin-ups-vs-pull-ups-the-difference-the-benefits-muscles-worked"},
    hspu:{title:"CrossFit: HSPU Technique",url:"https://www.crossfit.com/essentials/hspu-and-you-master-the-movement"},
    row:{title:"CrossFit: Ring Row",url:"https://www.crossfit.com/essentials/the-ring-row"},
    knee:{title:"AAOS Knee Conditioning Program",url:"https://orthoinfo.aaos.org/globalassets/pdfs/2023-rehab_knee.pdf"},
    hssKnee:{title:"HSS: Knee Strengthening",url:"https://www.hss.edu/health-library/move-better/exercises-strengthen-knees"},
    shoulder:{title:"AAOS Shoulder Conditioning Program",url:"https://orthoinfo.aaos.org/globalassets/pdfs/2024-rotator-cuff-and-shoulder-conditioning-program.pdf"},
    posterior:{title:"HSS: Posterior-Chain Exercises",url:"https://www.hss.edu/health-library/move-better/posterior-chain-strengthening"},
    hip:{title:"HSS: Hip Strengthening",url:"https://www.hss.edu/health-library/move-better/hip-strengthening-exercises"},
    stretch:{title:"Mayo Clinic: Stretching Guide",url:"https://www.mayoclinic.org/healthy-lifestyle/fitness/in-depth/stretching/art-20546848"},
    back:{title:"HSS: Back Exercises",url:"https://www.hss.edu/health-library/move-better/best-back-exercises"}
  };
  const sourceFor=id=>id==="hspu"?refs.hspu:id==="oap"?refs.nasmPush:id==="pushups"||id==="push-volume"||id==="press-up"?refs.push:id.includes("row")?refs.row:id==="pullups"||id==="pull-volume"||id==="hang"||id==="scap-pull"?refs.nasmPull:["shoulders-out","wall-slides","shoulder-stability","wrist-flex"].includes(id)?refs.shoulder:["hip-flexor","hip-90","mobilize","back-hip-flex"].includes(id)?refs.stretch:["glute-bridge","posterior-chain","back-one-leg","back-two-leg"].includes(id)?refs.posterior:id==="spine"?refs.back:["knee-tread","backward-tread","knee-flex","knee-ext","knee-stability","step-forward","step-back","step-side","long-calf","short-calf","front-shins","pistol","pistol-fri","squat-rock","ankle-wall"].includes(id)?refs.knee:refs.ace;
  function get(id,name){const s=specs[id]||{type:"standing",tempo:"Slow and controlled",feel:"The intended working muscles",easier:"Reduce the range",harder:"Increase range only with control"},tech=exact[id]||base[s.type]||base.standing;return {...s,...tech,source:sourceFor(id),frames:window.ATHLETIC_ILLUSTRATIONS.get(id,name)}}
  return {get,profiles:specs,instructions:exact,references:refs};
})();
